bpf:
  masquerade: true
cluster:
  id: 0
  name: default
containerRuntime:
  integration: containerd
encryption:
  nodeEncryption: false
endpointRoutes:
  enabled: true
hostFirewall:
  enabled: true
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv4PodCIDR: 244.16.0.0/12
    clusterPoolIPv4PodCIDRList:
    - 244.16.0.0/12
k8sServiceHost: 240.0.0.250
k8sServicePort: 6443
kubeProxyReplacement: partial
metrics:
  enabled:
  - dns:query;ignoreAAAA
  - drop
  - tcp
  - flow
  - icmp
  - http
operator:
  replicas: 1
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnel: geneve
