autoDirectNodeRoutes: true
bandwidthManager:
  enabled: true
bgpControlPlane:
  enabled: true
bpf:
  lbExternalClusterIP: true
  masquerade: true
cgroup:
  autoMount:
    enabled: true
  hostRoot: /run/cilium/cgroupv2
cluster:
  id: 0
  name: default
clustermesh:
  apiserver:
    enabled: true
    tls:
      auto:
        method: certmanager
  config:
    enabled: true
  useAPIServer: true
containerRuntime:
  integration: containerd
debug:
  enabled: true
devices: eth0
encryption:
  nodeEncryption: false
endpointRoutes:
  enabled: true
gatewayAPI:
  enabled: false
hostFirewall:
  enabled: true
hubble:
  enabled: true
  relay:
    enable: true
identityAllocationMode: kvstore
installIptablesRules: true
ipMasqAgent:
  enabled: true
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv4PodCIDR: 244.16.0.0/12
    clusterPoolIPv4PodCIDRList:
    - 244.16.0.0/12
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: 240.0.0.0/4
ipv6:
  enabled: false
k8s:
  requireIPv4PodCIDR: false
k8sServiceHost: 240.0.0.250
k8sServicePort: 6443
kubeProxyReplacement: strict
l7Proxy: true
localRedirectPolicy: true
metrics:
  enabled:
  - dns:query;ignoreAAAA
  - drop
  - tcp
  - flow
  - icmp
  - http
monitor:
  enabled: true
operator:
  replicas: 2
policyEnforcementMode: never
pprof:
  enabled: true
prometheus:
  enabled: true
rollOutCiliumPods: true
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tag: v1.12.7
tunnel: disabled
